trigger:
- master

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseNode@1
      inputs:
        version: '12.x'
      displayName: 'Install Node.js 12.x'

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
           npm | "$(Agent.OS)"
           npm
        path: $(npm_config_cache)
      displayName: Cache npm

    - script: |
        npm ci
        npm run build -- --dest dist
      displayName: 'npm ci and build'

    - publish: dist
      artifact: site
      displayName: 'Publish artifact'

- stage: Deploy
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: 'Azure Sponsorship'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  ip=$(curl -s https://ipinfo.io/json | jq -r .ip)
                  az storage account network-rule add --account-name $1 --ip-address $ip
                arguments: 'daruyanagi1'
              displayName: 'Adding IP Address to Firewall'

            - task: AzureCLI@2
              inputs:
                azureSubscription: 'Azure Sponsorship'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az storage blob sync --container '$web' --source "$(Pipeline.Workspace)/site/" --account-name $1
                arguments: 'daruyanagi1'
              displayName: 'Sync to Storage'

            - task: AzureCLI@2
              inputs:
                azureSubscription: 'Azure Sponsorship'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  ip=$(curl -s https://ipinfo.io/json | jq -r .ip)
                  az storage account network-rule remove --account-name $1 --ip-address $ip
                arguments: 'daruyanagi1'
              condition: always()
              displayName: 'Remove IP Address from Firewall'

        routeTraffic:
          steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: 'Azure Sponsorship'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az cdn endpoint purge -g DaruTest-RG -n static-daruyanagi --profile-name daruyanagi --content-paths '/*' --no-wait
                arguments: 'daruyanagi1'
              displayName: 'Purge CDN Cache'