name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [master]

env:
  NODE_VERSION: "16.x"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: npm ci and build
      run: |
        npm ci
        npm run build -- --dest dist

    - name: Deploy to Static Web App
      run: |
        npm i -g @azure/static-web-apps-cli
        swa deploy ./dist/ --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_ISLAND_0C11F9100 }}
