name: Publish

on:
  push:
    branches: [ master ]

env:
  AZURE_STORAGE_NAME: daruyanagi1
  NODE_VERSION: '14.x'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm ci and build
      run: |
        npm ci
        npm run build -- --dest dist

    - name: Installing CLI-beta for OpenID Connect
      run: |
        cd ../..
        CWD="$(pwd)"
        python3 -m venv oidc-venv
        . oidc-venv/bin/activate
        echo "activated environment"
        python3 -m pip install -q --upgrade pip
        echo "started installing cli beta"
        pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
        echo "***************installed cli beta*******************"
        echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Adding IP Address to Firewall
      run: |
        ip=$(curl -s https://ipinfo.io/json | jq -r .ip)
        az storage account network-rule add --account-name ${{ env.AZURE_STORAGE_NAME }} --ip-address $ip

    - name: Sync to Storage
      run: |
        for i in {1..5}; do
          az storage blob sync --container '$web' --source ./dist/ --account-name ${{ env.AZURE_STORAGE_NAME }} && break
          sleep 10
        done

    - name: Remove IP Address from Firewall
      run: |
        ip=$(curl -s https://ipinfo.io/json | jq -r .ip)
        az storage account network-rule remove --account-name ${{ env.AZURE_STORAGE_NAME }} --ip-address $ip

    - name: Purge CDN Cache
      run: |
        az cdn endpoint purge -g DaruTest-RG -n daruyanagi --profile-name daruyanagi --content-paths '/*' --no-wait
